name: Commit Compliance

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --no-tags --prune --depth=5 origin main

      - name: Commitsar check
        uses: docker://aevea/commitsar:0.15.0
